
const categories={
  Resturant:[
  { question: 'Can I Have a menu?' },
  { question: 'What is there to drink?' },
  { question: 'Can I have water?' },
  { question: 'How much is the bill?' },
  { question: 'What are the specials for today?' },
  { question: 'Can I have a new fork?' },
  { question: 'Can I have a new spoon?' },
  { question: 'Can I have a new knife?' },
  { question: 'Can I have a new Napkin?' },
  { question: 'Where is the restroom?' },
  { question: 'The name of(Waiter, Waitress, Chef, Manager, Busboy, Busgirl)' },
],
Travel:[
  {question:'Can you take me to ... ?'},
  {question:'Where is ... ?'},
  {question:'How far away is ... ?'},
  {question:'How far away is ... ?'},
  {question:'Where are good resturants to eat at?'},
  {question:' Where are there fun activities?'},
],
Introductions:[
  {question:'Goodmorning'},
  {question:'Goodnight'},
  {question:'How are you?'},
  {question:'How is your friend?'},
  {question:'How is your mom?'},
  {question:'How is your dad?'},
  {question:'How old are you?'},
  {question:'DO you have any siblings?'},
  {question:'What grade are you in?'},
  {question:'Whats your favorite food?'},
  {question:'What are your hobbies?'},
  {question:'Can you describe your friend?'},
  {question:'Where do you live?'},
  {question:'Where did you grow up?'},
  {question:'What country did you originate from?'},
  {question:'What is your job?'},
  {question:'Where is your job?'},
],
NewsAndWeather:[
{question:'The weather is good today.'},
{question:'Is it bad weather?'},
{question:'What is the weather for today?'},
{question:'What is the weather for tomorrow?'},
{question:'Is it going to rain tomorrow?'},
{question:'Is it going to snow tomorrow?'},
{question:'What is the temperature outside?'},
{question:'What is the score between the two teams?'},
],
HouseObjects:[
  {question:'Living Room'},
  {question:'Television'},
  {question:'Desk'},
  {question:'Chair'},
  {question:'Water Bottle'},
  {question:'Telephone/Phone'},
  {question:'Computer'},
  {question:'Kitchen'},
  {question:'Knife'},
  {question:'Spoon'},
  {question:'Fork'},
  {question:'Napkin'},
  {question:'Sink'},
  {question:'Bathroom'},
  {question:'Washing machine'},
  {question:'Dryer'},
  {question:'Soap'},
  {question:'Shower'},
  {question:'Bath'},
  {question:'laundry'},
  {question:'basket'},
  {question:'House'},
  {question:'Apartment'},
],
School:[
  {question:'School'},
  {question:'Bus'},
  {question:'Desk'},
  {question:'Chair'},
  {question:'Teacher'},
  {question:'Professor'},
  {question:'Student'},
  {question:'Chalkboard/Whiteboard'},
  {question:'Pencil'},
  {question:'Paper'},
  {question:'Pen'},
  {question:'Binder'},
  {question:'Mask'},
  {question:'Folder'},
  {question:'Backpack'},
  {question:'Eraser'},
  {question:'Computer'},
  {question:'Hallway'},
  {question:'Library'},
  {question:'Gym class'},
  {question:'Language Arts class'},
  {question:'English Class/ ELA'},
  {question:'Social Studies/ History class'},
  {question:'Math class'},
  {question:'Science class'},
  {question:'Cafeteria'},
]
}

export default categories;